targets:
  $default:
    builders:
      :messages_builder:
        enabled: true

builders:
  messages_builder:
    import: "tools/builders/messages_builder.dart"
    builder_factories: ["messagesBuilder"]
    build_extensions: {"$lib$": ["src/generated/messages.g.dart"]}
    build_to: source
