name: Update from bahai.org and release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update_messages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Build
        run: dart run build_runner build -d
      - name: Check git status
        id: status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "STATUS=changed" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.status.outputs.STATUS == 'changed' }}
        run: dart analyze # && dart test
      - if: ${{ steps.status.outputs.STATUS == 'changed' }}
        uses: peter-evans/create-pull-request@v6
        with:
          title: Auto-update from bahai.org
          commit-message: Auto-update from bahai.org
          branch: autorelease
      - if: ${{ steps.status.outputs.STATUS == 'changed' }}
        name: Setup pub.dev credentials
        env:
          PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
        run: |
          mkdir -p $HOME/.config/dart
          echo "$PUB_DEV_CREDENTIALS" > $HOME/.config/dart/pub-credentials.json
      - if: ${{ steps.status.outputs.STATUS == 'changed' }}
        name: Check Publish Warnings
        run: dart pub publish --dry-run
      # - if: ${{ steps.status.outputs.STATUS == 'changed' }}
      #   name: Publish Package
      #   run: dart pub publish -f
  
