name: Update from bahai.org and release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update_messages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: autorelease
          fetch-depth: 0
      - uses: dart-lang/setup-dart@v1
      - run: git rebase main
      - run: dart pub get
      - name: Build
        run: dart run build_runner build -d
      - name: Check git status
        id: status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "STATUS=changed" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.status.outputs.STATUS == 'changed' }}
        run: dart analyze # && dart test
      - if: ${{ steps.status.outputs.STATUS == 'changed' }}
        uses: stikkyapp/update-pubspec-version@v2
        id: pubspec
        with:
          strategy: none
          bump-build: true
          path: './pubspec.yaml'
      - if: ${{ steps.status.outputs.STATUS == 'changed' }}
        run: |
          VERSION="v${{ steps.pubspec.outputs.new-version }}"
          git add .
          git commit -m "auto update from bahai.org to ${VERSION}"
          git tag "${VERSION}"
          git push origin autorelease
          git push origin --tags
