name: Update from bahai.org and release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update_messages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Build
        run: dart run build_runner build -d
      - name: Check git status
        id: status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "STATUS=changed" >> $GITHUB_OUTPUT
          fi
      - if: "${{ steps.status.outputs.STATUS == 'changed' }}"
        run: dart analyze
      - if: "${{ steps.status.outputs.STATUS == 'changed' }}"
        run: echo UPDATE ME
      # - run: dart test
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
